ALTER TABLE zy_education MODIFY COLUMN MAJOR VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci,
 MODIFY COLUMN `DEGREEID` INTEGER UNSIGNED,
 MODIFY COLUMN `STARTYEAR` INTEGER UNSIGNED,
 MODIFY COLUMN `STARTMONTH` INTEGER UNSIGNED,
 MODIFY COLUMN `ENDYEAR` INTEGER UNSIGNED,
 MODIFY COLUMN `ENDMONTH` INTEGER UNSIGNED;